### ISSUE TITLE
Another Expired TLS Certificate 2022-11-05

### ISSUE THREAD

**Issue by JiaZhangJiaZhangJiaZhangJiaZhang** [arindas/manjarno#16]
FYI:
https://forum.manjaro.org/t/expired-ssl-certificate-on-archived-forum-manjaro-org/126131

**Comment by arindas** [comment]
Well it's for the public discussion forum. It's not meant for software distribution, right? So, a manjaro user is not directly affected if they don't use the forum.

Still, at this point, someone ought to setup a background health checker of sorts just to detect when their SSL certificates expire and then post about it somewhere automatically. How difficult can configuring nginx with certbot be?

I'll be closing this issue since it's not related to their software distribution channels. Still thanks for informing.
